In [23]:
# EJERCICIO 1 

# Calcula la longitud de una cadena de texto sin usar la instruccion len(cadena)

# 1) Cadena de texto: hola como estas?

    # Nombre de la variable: "cadena"


cadena_texto = "hola como estas?" 
print(cadena_texto)
# 2) Longitud de la cadena de texto

print(len(cadena_texto))

# 3) Longitud de la cadena de texto calculada con un bucle

def longitud_cadena (cadena):
    contador = 0
    for i in cadena:
        contador+=1
    return contador

print("La cadena `", cadena_texto, "´ tiene ",longitud_cadena(cadena_texto), " caracteres")

hola como estas?
16
La cadena ` hola como estas? ´ tiene  16  caracteres


In [24]:
# EJERCICIO 2

# Crea un diccionario que tenga la nota de 3 asignaturas y

# haz un pequeño algoritmo que calcule la nota media

# CURSO         -> Nota
# ---------------------
# Python        ->  10
# Big Data      ->  8
# NLP           ->  6

curso = ["Python","Big Data","NLP"]
nota = [10,8,6]

notas_clase = {'Python': 10, 'Big Data': 8, 'NLP': 6}
notas_clase

#creamos un listado de los valores

values = list(notas_clase.values())
print(values)

#values = [value for value in notas_clase.values()]
#print(values)

media = sum(values)/len(values)
print(media)


[10, 8, 6]
8.0


In [25]:
# 1) Muestra el valor de las claves

notas_clase.keys()

dict_keys(['Python', 'Big Data', 'NLP'])

In [26]:
# 2) Muestra el valor de los valores del diccionario

notas_clase.values()

dict_values([10, 8, 6])

In [27]:
# 3) Apendiza en el diccionario un nuevo elemento:

    # Machine Learning --> 9
notas_clase["Machine Learning"]=9
print(notas_clase)

{'Python': 10, 'Big Data': 8, 'NLP': 6, 'Machine Learning': 9}


In [28]:
# 4) Haciendo uso un bucle muestra la clave y el valor del diccionario, cuyo resultado final sean listas anidadas.

    # [["clave1", valor1], ["clave2", valor2]]
lista_anidada=[]
for key, value in notas_clase.items():
    lista_intermedia=[]
    lista_intermedia.append(key)
    lista_intermedia.append(value)
    lista_anidada.append(lista_intermedia)
print(lista_anidada)

#lista_anidada=[]
#for key in notas_clase.items():
#    lista_intermedia=[]
#    lista_intermedia.append(key)
#    print(lista_intermedia)
#    lista_anidada.append(lista_intermedia)
#    print(lista_intermedia)
#print(lista_anidada)

[['Python', 10], ['Big Data', 8], ['NLP', 6], ['Machine Learning', 9]]


In [29]:
# FUNCION
def lista_anidada (lista):
    lista_anidada=[]
    for key, value in lista.items():
        lista_intermedia=[]
        lista_intermedia.append(key)
        lista_intermedia.append(value)
        lista_anidada.append(lista_intermedia)
    return lista_anidada

print(lista_anidada(notas_clase))

[['Python', 10], ['Big Data', 8], ['NLP', 6], ['Machine Learning', 9]]


In [137]:
# 5) Reconvierte el diccionario para transformarlo en un dataframe y busca la asignatura con la nota más alta
import pandas as pd

curso = ["Python", "Big Data", "NLP", "Machine Learning"]
nota = [10,8,6,9]

notas_clase_dic = {"Asignaturas": curso, 'Notas': nota}
print(notas_clase_dic)

df_diccionario = pd.DataFrame(notas_clase_dic)
print(df_diccionario)

mayor = max(df_diccionario.Notas)


{'Asignaturas': ['Python', 'Big Data', 'NLP', 'Machine Learning'], 'Notas': [10, 8, 6, 9]}
        Asignaturas  Notas
0            Python     10
1          Big Data      8
2               NLP      6
3  Machine Learning      9
10


In [139]:
# 6) ¿y la nota más baja?
nota_minima = min(df_diccionario.Notas)
print(nota_minima)

6


In [150]:
# 7) Ordena el dataframe en orden descendente:
df_diccionario.sort_values(by='Notas', ascending=False)
df_diccionario.sort_values(by='Asignaturas', ascending=True)

Asignaturas  Notas
1          Big Data      8
3  Machine Learning      9
2               NLP      6
0            Python     10

In [151]:
# funcion
def ordenar_diccionario(diccionario, columna, tipo):
    diccionario.sort_values(by=columna, ascending=tipo)
    return diccionario

ordenar_diccionario(df_diccionario, "Notas", False)

Asignaturas  Notas
0            Python     10
1          Big Data      8
2               NLP      6
3  Machine Learning      9

In [34]:
# EJERCICIO 3
# """
# Dadas 2 funciones:
# Determina cual de ellas ejecuta mas rápido.
# Si sabes, hazlo de 2 formas.
# función a
# def main(): for i in range(10**8): pass
# main()
# función b
# def main(): for i in np.arange(10**8): pass
# main()
# de 2 formas

import time
import numpy as np

In [209]:
# función a
%time

def main():
    for i in range(10**8):
        pass

main()


CPU times: total: 0 ns
Wall time: 0 ns


In [210]:
# función b
%time
def main():
    for i in np.arange(10**8):
        pass
main()

CPU times: total: 0 ns
Wall time: 0 ns


In [36]:
# función a
x1 = time.time()
def main():
    for i in range(10**8):
        pass
main()

y1 = time.time()

tiempo1 = y1-x1


In [37]:
# función b
x2 = time.time()
def main():
    for i in np.arange(10**8):
        pass
main()

y2 = time.time()
tiempo2 = y2-x2

print("Tiempo 1ºFuncion ", tiempo1, "Tiempo 2ºFuncion ", tiempo2) 

Tiempo 1ºFuncion  3.759249210357666 Tiempo 2ºFuncion  7.491258144378662


In [35]:
# FUNCION comparar
tiempo1 = 0
tiempo2 = 0
def comparar_funciones(operacion1, operacion2):
    x1 = time.time()
    def main1():
        for i in operacion1:
            pass
    main1()

    y1 = time.time()

    tiempo1 = y1-x1

    x2 = time.time()
    def main2():
        for i in operacion2:
            pass
    main2()

    y2 = time.time()
    tiempo2 = y2-x2
    return(print("Tiempo 1ºFuncion ", tiempo1, "Tiempo 2ºFuncion ", tiempo2)) 


comparar_funciones(range(10**8), np.arange(10**8))

 

Tiempo 1ºFuncion  3.5130574703216553 Tiempo 2ºFuncion  7.728407859802246


In [166]:
# EJERCICIO 4

# Dada:

# Una matriz tal que así:

# A = np.array([[1,2,3], [4,5,6], [7,8,9]])

# se pide:

# 1) Escribe ese código en Python

# 2) Escribe la matriz transpuesta.

    # Nota, puedes usar numpy, si quieres. Si sabes más de una forma puedes usar varias.

# 3) Se pide que hagas lo mismo, pero con un bucle.

In [38]:
# 1) Escribe ese código en Python
A = np.array([[1,2,3], 
              [4,5,6], 
              [7,8,9]])
A

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [236]:
# 2) Escribe la matriz transpuesta.
A.T

array([[1, 4, 7],
       [2, 5, 8],
       [3, 6, 9]])

In [278]:
A.transpose()

array([[1, 4, 7],
       [2, 5, 8],
       [3, 6, 9]])

In [45]:
# 3) Se pide que hagas lo mismo, pero con un bucle.

def transponer_matriz(matriz):
    matriz_transpuesta = np.empty((3, 3), int)
    if len(matriz) == 0:
        return []
    
    for i in range(len(matriz)):
        for j in range(len(matriz)):
            matriz_transpuesta[i][j] = matriz[j][i]
    return matriz_transpuesta


transponer_matriz(A)

array([[1, 4, 7],
       [2, 5, 8],
       [3, 6, 9]])

In [46]:
def transponer_matriz2(matriz):
    if len(matriz) == 0:
        return []
    
    matriz_transpuesta = np.array([[matriz[i][j] for i in range(len(matriz))] for j in range(len(matriz))])
    return matriz_transpuesta

transponer_matriz2(A)

array([[1, 4, 7],
       [2, 5, 8],
       [3, 6, 9]])