In [1]:
# Ejercicio 1

# Crea una matriz con ayuda numpy:
# 1) Cuya matriz contenga 4 filas por 4 columnas de ceros

import numpy as np

In [153]:
matriz = np.zeros((4,4))
print(matriz)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [152]:
# 2) A partir de la matriz de ceros crea la matriz identidad

def Matriz_Identidad (M):
    Matriz_I = np.zeros((4,4))
    for i in range(len(M)):
        for j in range(len(M[i])):
            if i == j:
                Matriz_I[i][j] = 1
    return Matriz_I

print(Matriz_Identidad(matriz))

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


In [157]:
# EJERCICIO 2

# Crea una matriz con ayuda numpy:

# Primera fila contenga: 3, 6, 8
# Segunda fila contenga: 20, 5, 7
# Tercera fila contenga: 10, 14, 1

matriz = np.array([[3,6,8],
                  [20,5,7],
                  [10,14,1]])
print(matriz)
print(type(matriz))

[[ 3  6  8]
 [20  5  7]
 [10 14  1]]
<class 'numpy.ndarray'>


In [158]:
# 1) Crea la transpuesta de esta matriz

print(matriz.T)

print(np.transpose(matriz))

[[ 3 20 10]
 [ 6  5 14]
 [ 8  7  1]]
[[ 3 20 10]
 [ 6  5 14]
 [ 8  7  1]]


In [160]:
# 2) Muestra el tamaño de la matriz

print(matriz.size)


9


In [77]:
# 3) Muestra las dimensiones

print(matriz.shape)

(3, 3)


In [78]:
# 4) ¿La matriz tiene valores menores de 0?

np.all(matriz<0)

False

In [79]:
# 5) ¿La matriz tiene algún valor mayor de 10?

np.any(matriz<10)

True

In [80]:
# 6) Coge una muestra de 5 valores de esa matriz usando linespace
def Obtener_Muestreo (M, valores):
    muestreo = np.linspace(M.min(),M.max(),valores)
    return muestreo

muestra = Obtener_Muestreo (matriz, 5)
print(muestra)

[ 1.    5.75 10.5  15.25 20.  ]


In [81]:
# 7) La matriz contiene el valor 7

def Buscar_Valor(M, valor):
    if valor in M:
        return(print("El valor", valor, "está en la matriz"))
    else:
        return(print("El valor", valor, "NO está en la matriz"))

Buscar_Valor(matriz, 7)

El valor 7 está en la matriz


In [82]:
# 8) Crea una copia de esa matriz en una única dimensión

copia_matriz = matriz.flatten()
copia_matriz

array([ 3,  6,  8, 20,  5,  7, 10, 14,  1])

In [129]:
# 9) Crea una copia de esa matriz en una única dimensión, en este caso usando un bucle y una lista vacia
def Copia_Matriz_1_Dimension(M):
    copia_matriz = []
    for i in range(len(M)):
        for j in range(len(M[i])):
            copia_matriz.append(M[i][j])
    return copia_matriz

Matriz_1 = np.array(Copia_Matriz_1_Dimension(matriz))
Matriz_1


array([ 3,  6,  8, 20,  5,  7, 10, 14,  1])

In [98]:
# 10) Realiza a esta última matriz creada con flatten la potencia de 3
pow(Matriz_1,3)

array([  27,  216,  512, 8000,  125,  343, 1000, 2744,    1], dtype=int32)

In [63]:
def Potencia_Matriz(M, potencia):
    return pow(M,potencia)

Potencia_Matriz(Matriz_1, 3)

array([  27,  216,  512, 8000,  125,  343, 1000, 2744,    1], dtype=int32)

In [169]:
def Potencia_Matriz(M, potencia):
    M_potencia = []
    for i in range(len(M)):
        for j in range(len(M[i])):
            M_potencia.append(M[i][j]**potencia)
    return M_potencia

Matriz_1 = np.array(Potencia_Matriz(matriz,3))
Matriz_1

array([  27,  216,  512, 8000,  125,  343, 1000, 2744,    1])