In [1]:
# Ejercicio 1
# 1) Haz un programa que calcule los múltiplos de 3
# Para ello primero primero debe preguntarse al usuario cuántos múltiplos desea añadir.
# Nota: Puedes usar un bucle while si lo deseas

In [2]:
import numpy as np
import pandas as pd

In [98]:

def Multiplos (x):
    lista=list(range(3,(3*x)+1,3))
    return lista

x = int(input("¿cuántos múltiplos de 3 quieres imprimir?: "))
Multiplos(x)

¿cuántos múltiplos de 3 quieres imprimir?: 3


[3, 6, 9]

In [17]:
for numero in lista:
    print(numero)

3
6
9


In [34]:
def Multiplos (cifra, cantidad):
    lista=list(range(cifra,(cifra*cantidad)+1,cifra))
    for numero in lista:
        print(numero)
    return

x = int(input("¿cuántos múltiplos de 3 quieres imprimir?: "))
Multiplos(3,x)

¿cuántos múltiplos de 3 quieres imprimir?: 6
3
6
9
12
15
18


In [39]:
def Multiplos (cifra, cantidad):
    lista_nueva=[]
    lista=list(range(cifra,(cifra*cantidad)+1,cifra))
    for numero in lista:
        lista_nueva.append(numero)
    return(lista_nueva)

x = int(input("¿cuántos múltiplos de 3 quieres imprimir?: "))
Multiplos(3,x)

¿cuántos múltiplos de 3 quieres imprimir?: 6


[3, 6, 9, 12, 15, 18]

In [41]:
def Multiplos (cifra, cantidad):
    lista_nueva=[]
    i=0
    while i<cantidad:
        i=i+1
        lista_nueva.append(3*i)
    return(lista_nueva)

x = int(input("¿cuántos múltiplos de 3 quieres imprimir?: "))
Multiplos(3,x)

¿cuántos múltiplos de 3 quieres imprimir?: 6


[3, 6, 9, 12, 15, 18]

In [42]:
# 2) Haz lo mismo con np.arange

In [43]:
x = int(input("¿cuántos múltiplos de 3 quieres imprimir?: "))
x

¿cuántos múltiplos de 3 quieres imprimir?: 3


3

In [44]:
np.arange(3,(3*x)+1,3)

array([3, 6, 9])

In [99]:
x = int(input("¿cuántos múltiplos de 3 quieres imprimir?: "))
x
def Multiplos (cifra, cantidad):
    lista = list(np.arange(cifra,(cifra*cantidad)+1,cifra))
    return lista

print(Multiplos(3,x))

¿cuántos múltiplos de 3 quieres imprimir?: 3
[3, 6, 9]


In [102]:
# EJERCICIO 2

# """
#     Dado el listado del apartado 2
#     Dada esta lista de variable "listado" y "valores": 10, 10, 20, 20, 20, 30, 40
#     Se pide:
# """

# 1) Crea un DataFrame con esa información e imprímelo

listado = [10, 10, 20, 20, 20, 30, 40]

df = pd.DataFrame({"listado": listado})

df


listado
0       10
1       10
2       20
3       20
4       20
5       30
6       40

In [103]:
# 2) Usa value_counts() para determinar cuántas repeticiones hay de cada número en esa columna

df.listado.value_counts()

20    3
10    2
30    1
40    1
Name: listado, dtype: int64

In [104]:
# 3) Haz un ".shape" a esa información del value_counts()

    # NOTA: Escribe: .shape justo al final


df.listado.value_counts().shape

(4,)

In [105]:
# 4) A esa misma instrucción con value_counts() escribe al final ".values"

    # Y veras la información..

    # pasa esa información a lista si puedes

    # y guarda ese listado como "repeticiones"

print(df.listado.value_counts().values)

repeticiones=list(df.listado.value_counts().values)
print(repeticiones)

[3 2 1 1]
[3, 2, 1, 1]


In [106]:
# 5) A esa información de value_counts() añade al final ".index"

    # Y pasa posteriormente a lista esa información

    # y guarda ese listado con el nombre: "valores"

    
print(df.listado.value_counts().index)

valores=list(df.listado.value_counts().index)
print(valores)

Int64Index([20, 10, 30, 40], dtype='int64')
[20, 10, 30, 40]


In [107]:
# 6) Crea un DataFrame con 2 columnas,

    # 1 para "valores"

    # 1 para "repeticiones"

    # llámalo: "df_value_counts" (por ejemplo)

    # Y observa..

df_value_count=pd.DataFrame({"valores":valores, "repeticiones":repeticiones})
df_value_count

valores  repeticiones
0       20             3
1       10             2
2       30             1
3       40             1

In [110]:
# 7) Haz lo siguiente: "df.value_counts()"

df.value_counts()


listado
20         3
10         2
30         1
40         1
dtype: int64

In [ ]:
# 8) Observa si hay diferencias entre: "df" y "df_value_counts"

#es lo mismo

In [74]:
# EJERCICIO 3
# """
#     Comparación de matrices
#     Haz el código que testee si esas 2 matrices son iguales
#     1)
#     Dadas:
#    matriz1 = np.array([[1,2],[3,4]])
#     matriz2 = np.array([[1,2],[3,8]])
#     PISTAS:
#     -1- RECORRER MATRIZ1 Y MATRIZ2 CON LA PARAMETRIZACIÓN de i y j
#     COMPROBAR: ( matriz1 [ i ][ j ] == matriz2 [ i ][ j ] )

In [75]:
matriz1 = np.array([[1,2],[3,4]])
matriz2 = np.array([[1,2],[3,8]])

In [78]:
print(matriz1)
print(matriz2)

[[1 2]
 [3 4]]
[[1 2]
 [3 8]]


In [85]:
matriz1.shape[0]

2

In [89]:
matriz1.shape[0]

2

In [117]:
def compara_matrices (M1,M2):

    diferentes=False
    if (M1.shape[0]==M2.shape[0]) and (M1.shape[1]==M2.shape[1]):
        for i in range(M1.shape[0]):
            for j in range(M1.shape[1]):
                if M1[i][j] != M2[i][j]:
                    diferentes=True
                    break
    else:
        return print("Son de diferentes dimensiones")
    
    if diferentes:
        return print("Son diferentes matrices")
    else:
        return print("Son iguales")

compara_matrices(matriz1,matriz2)

Son diferentes matrices


In [112]:
def compara_matrices (M1,M2):
    return (M1==M2).all()

compara_matrices(matriz1,matriz2)

False

In [121]:
# -4- puedes usar np.arange( ) si lo deseas para las filas y para las columnas


def compara_matrices (M1,M2):

    diferentes=False
    if (M1.shape[0]==M2.shape[0]) and (M1.shape[1]==M2.shape[1]):
        for i in np.arange(M1.shape[0]):
            for j in np.arange(M1.shape[1]):
                if M1[i][j] != M2[i][j]:
                    diferentes=True
                    break
    else:
        return print("Son de diferentes dimensiones")
    
    if diferentes:
        return print("Son diferentes matrices")
    else:
        return print("Son iguales")

compara_matrices(matriz1,matriz2)

Son diferentes matrices


In [119]:
#-5- recuerda el ejercicio del cronómetro para tener una referencia

In [122]:
import time
inicio = time.time()

def compara_matrices (M1,M2):

    diferentes=False
    if (M1.shape[0]==M2.shape[0]) and (M1.shape[1]==M2.shape[1]):
        for i in range(M1.shape[0]):
            for j in range(M1.shape[1]):
                if M1[i][j] != M2[i][j]:
                    diferentes=True
                    break
    else:
        return print("Son de diferentes dimensiones")
    
    if diferentes:
        return print("Son diferentes matrices")
    else:
        return print("Son iguales")

compara_matrices(matriz1,matriz2)

fin = time.time()

print("range", fin-inicio)

inicio = time.time()

def compara_matrices (M1,M2):

    diferentes=False
    if (M1.shape[0]==M2.shape[0]) and (M1.shape[1]==M2.shape[1]):
        for i in np.arange(M1.shape[0]):
            for j in np.arange(M1.shape[1]):
                if M1[i][j] != M2[i][j]:
                    diferentes=True
                    break
    else:
        return print("Son de diferentes dimensiones")
    
    if diferentes:
        return print("Son diferentes matrices")
    else:
        return print("Son iguales")

compara_matrices(matriz1,matriz2)

fin = time.time()

print("np.arange", fin-inicio)

inicio = time.time()

def compara_matrices (M1,M2):
    return (M1==M2).all()

compara_matrices(matriz1,matriz2)

fin = time.time()

print(".all", fin-inicio)

Son diferentes matrices
range 0.0010013580322265625
Son diferentes matrices
np.arange 0.0010018348693847656
.all 0.0
